<?php
namespace common\modules;



use Yii;
use yii\web\Application;

class AdminModule extends \yii\easyii2\AdminModule
{
    public function init()
    {
        if(!$this->installed) {
            Yii::$app->on(Application::EVENT_BEFORE_ACTION, [$this, 'redirectInstall']);
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function redirectInstall()
    {
        if(Yii::$app->controller->route == 'site/index'){
            Yii::$app->response->redirect(['install/step1'])->send();
            Yii::$app->end();
        }
    }
}